const sequelize = require('../db')
const { DataTypes } = require('sequelize')

const Orgs = sequelize.define('orgs', {
    idlistedu: DataTypes.STRING,
    id_parent: DataTypes.STRING,
    id_givc: DataTypes.STRING,
    id_spr_min: DataTypes.STRING,
    id_rubpnubp: DataTypes.STRING,
    id_level: DataTypes.STRING,
    name: DataTypes.STRING,
    name_abb: DataTypes.STRING,
    inn: DataTypes.STRING,
    kpp: DataTypes.STRING,
    id_region: DataTypes.STRING,
    address: DataTypes.STRING,
    ogrn: DataTypes.STRING,
    date_remove: DataTypes.DATE,
    kod_status_egrul: DataTypes.STRING,
    status_egrul: DataTypes.STRING,
    okpo: DataTypes.STRING,
    name_rub: DataTypes.STRING,
    egrul_updated: DataTypes.DATE,
    phone: DataTypes.STRING,
    site: DataTypes.STRING,
    mail: DataTypes.STRING,
    recordnum_rub: DataTypes.STRING,
    inn_rub: DataTypes.STRING,
    kpp_rub: DataTypes.STRING,
    okved: DataTypes.STRING,
    date_start_egrul: DataTypes.DATE,
    oktmo: DataTypes.STRING,
    okfs: DataTypes.STRING,
    egrul_uchred: DataTypes.STRING,
    kod_status_rub: DataTypes.STRING,
    kbkcode: DataTypes.STRING,
    kbkname: DataTypes.STRING,
    budgetlvlcode: DataTypes.STRING,
    org_type: DataTypes.STRING,
    heads: DataTypes.STRING,
    inclusiondate: DataTypes.DATE,
    shortname: DataTypes.STRING,
    opf_code: DataTypes.STRING,
    okfsname: DataTypes.STRING,
    kofkcode: DataTypes.STRING,
    budgetcode: DataTypes.STRING,
    budgetname: DataTypes.STRING,
    code_spobul: DataTypes.STRING,
    name_spobul: DataTypes.STRING,
    is_reorg: DataTypes.BOOLEAN,
    tz_org: DataTypes.STRING,
    ogrn_rub: DataTypes.STRING,
    oktmoname: DataTypes.STRING,
    org_create_date: DataTypes.DATE
}, {
    tableName: 'orgs',
    timestamps: false
})

module.exports = { Orgs }
